# Generated by Django 3.1.3 on 2020-11-15 05:14

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employeeDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=15, null=True)),
                ('first_name', models.CharField(max_length=24)),
                ('last_name', models.CharField(blank=True, max_length=24, null=True)),
                ('address', models.TextField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=64)),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
